name: Setup Unix dependencies
description: ''

runs:
  using: composite
  steps:
    - uses: DeterminateSystems/nix-installer-action@v17
    - uses: DeterminateSystems/magic-nix-cache-action@v9

    - shell: bash
      run: nix run .#gha-nix-develop -- .#runner
