name: Setup Unix dependencies
description: ''

runs:
  using: composite
  steps:
    - uses: DeterminateSystems/nix-installer-action@v12
    - uses: DeterminateSystems/magic-nix-cache-action@v7

    - shell: bash
      run: nix run .#gha-nix-develop -- .#runner
