name: Setup runner environment
description: Load runner shell environment, setup cache, install dependencies

runs:
  using: composite
  steps:
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Load Nix runner shell environment
      shell: bash
      run: nix run .#gha-nix-develop -- .#runner
    - name: Setup PNPM cache
      uses: actions/setup-node@v4
      with:
        cache: pnpm
    - name: Install PNPM dependencies
      shell: bash
      run: pnpm install
