name: Setup runner
description: ''

inputs:
  shell:
    description: INTERNAL
    default: ${{ runner.os == 'Windows' && 'powershell' || 'bash' }}

runs:
  using: composite
  steps:
    - if: runner.os != 'Windows'
      uses: ./.github/actions/dependencies-unix

    - if: runner.os == 'Windows'
      uses: ./.github/actions/dependencies-windows

    - uses: actions/setup-node@v4
      with:
        cache: pnpm

    - uses: actions/setup-go@v5
      with:
        cache-dependency-path: '**/*.sum'

    - shell: ${{ inputs.shell }}
      run: pnpm install

    - shell: ${{ inputs.shell }}
      run: go install tool
