// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package usersdb

import (
	"database/sql"
)

type User struct {
	ID           []byte
	Email        string
	PasswordHash []byte
	PlatformType sql.NullInt64
	PlatformID   sql.NullString
}
