version: "2"

run:
  allow-parallel-runners: false
  modules-download-mode: readonly
  allow-serial-runners: true
  go: "1.24"

linters:
  settings:
    staticcheck:
      checks:
        - all
        - "-ST1000"
        - "-ST1003"
        - "-ST1016"
        - "-ST1020"
        - "-ST1021"
        - "-ST1022"
        - "-S1016" ## False Positives
        - "-SA5011" ## False Positives
