version: "2"

run:
  allow-parallel-runners: true

linters:
  settings:
    staticcheck:
      checks:
        - all
        - "-ST1000"
        - "-ST1003"
        - "-ST1016"
        - "-ST1020"
        - "-ST1021"
        - "-ST1022"
        - "-S1016" ## False Positives
        - "-SA5011" ## False Positives
