branch_whitelist = ["prod"]
ignore_merge_commits = true

pre_bump_hooks = ["pnpm version --no-git-tag-version {{version}}"]
post_bump_hooks = ["git push", "git push origin {{version}}"]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
owner = "DevToolsGit"
repository = "api-recorder"
authors = [{ signature = "Tomas Zaluckij", username = "Tomaszal" }]
