packages:
  - apps/*
  - tools/*
  - packages/*

onlyBuiltDependencies:
  - '@bufbuild/buf'
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - bufferutil
  - electron
  - electron-winstaller
  - es5-ext
  - esbuild
  - keccak
  - lmdb
  - msgpackr-extract
  - nx
  - oxc-resolver
  - secp256k1
  - sharp
  - unrs-resolver
  - utf-8-validate

overrides:
  '@types/eslint': '-'

patchedDependencies:
  '@nx/eslint': patches/@nx__eslint.patch
  '@react-stately/table': patches/@react-stately__table.patch
