packages:
  - apps/*
  - tools/*
  - packages/*
  - packages/auth/*

catalog:
  '@aikidosec/safe-chain': 1.4.0
  '@alloy-js/cli': 0.22.0
  '@alloy-js/core': 0.22.0
  '@alloy-js/typescript': 0.22.0
  '@bufbuild/buf': 1.63.0
  '@bufbuild/protobuf': 2.10.2
  '@bufbuild/protoc-gen-es': 2.10.2
  '@bufbuild/protovalidate': 1.1.0
  '@codemirror/autocomplete': 6.20.0
  '@codemirror/commands': 6.10.1
  '@codemirror/lang-html': 6.4.11
  '@codemirror/lang-javascript': 6.2.4
  '@codemirror/lang-json': 6.0.2
  '@codemirror/lang-xml': 6.1.0
  '@codemirror/language': 6.12.1
  '@codemirror/state': 6.5.3
  '@codemirror/view': 6.39.9
  '@connectrpc/connect': 2.1.1
  '@connectrpc/connect-node': 2.1.1
  '@connectrpc/connect-query': 2.2.0
  '@connectrpc/connect-web': 2.1.1
  '@effect-atom/atom-react': 0.4.4
  '@effect/cli': 0.73.0
  '@effect/platform': 0.94.1
  '@effect/platform-browser': 0.74.0
  '@effect/platform-node': 0.104.0
  '@eslint/compat': 2.0.0
  '@eslint/js': 9.39.2
  '@faker-js/faker': 10.2.0
  '@fontsource-variable/dm-sans': 5.2.8
  '@fontsource/dm-mono': 5.2.7
  '@hookform/devtools': 4.4.0
  '@hookform/resolvers': 5.2.2
  '@lezer/generator': 1.8.0
  '@lezer/highlight': 1.2.3
  '@lezer/lr': 1.4.7
  '@nx/eslint': 22.4.2
  '@nx/js': 22.4.2
  '@nx/react': 22.4.2
  '@nx/storybook': 22.4.2
  '@nx/vite': 22.4.2
  '@nx/web': 22.4.2
  '@octokit/auth-action': 6.0.2
  '@octokit/rest': 22.0.1
  '@openreplay/tracker': 17.1.3
  '@prettier/plugin-xml': 3.4.2
  '@react-aria/collections': 3.0.1
  '@standard-schema/spec': 1.1.0
  '@storybook/addon-docs': 10.1.11
  '@storybook/react': 10.1.11
  '@storybook/react-vite': 10.1.11
  '@tailwindcss/typography': 0.5.19
  '@tailwindcss/vite': 4.1.18
  '@tanstack/eslint-plugin-router': 1.141.0
  '@tanstack/react-db': 0.1.60
  '@tanstack/react-query': 5.90.16
  '@tanstack/react-query-devtools': 5.91.2
  '@tanstack/react-router': 1.145.7
  '@tanstack/react-router-devtools': 1.145.7
  '@tanstack/router-plugin': 1.145.10
  '@tanstack/virtual-file-routes': 1.145.4
  '@tsconfig/strictest': 2.0.8
  '@types/eslint-plugin-jsx-a11y': 6.10.1
  '@types/node': 25.0.3
  '@types/react': 19.2.7
  '@types/react-dom': 19.2.3
  '@types/react-timeago': 8.0.0
  '@typescript-eslint/parser': 8.52.0
  '@typespec/compiler': 1.7.1
  '@typespec/emitter-framework': 0.14.0
  '@typespec/prettier-plugin-typespec': 1.7.0
  '@uiw/react-codemirror': 4.25.4
  '@vitejs/plugin-react': 5.1.2
  '@xyflow/react': 12.10.0
  babel-plugin-react-compiler: 19.1.0-rc.3
  better-auth: 1.2.9
  builder-util-runtime: 9.5.1
  drizzle-orm: 0.44.2
  effect: 3.19.14
  electron: 39.2.7
  electron-builder: 26.3.1
  electron-devtools-installer: 4.0.0
  electron-vite: 5.0.0
  eslint: 9.39.2
  eslint-config-prettier: 10.1.8
  eslint-import-resolver-typescript: 4.4.4
  eslint-plugin-better-tailwindcss: 3.8.0
  eslint-plugin-import-x: 4.16.1
  eslint-plugin-jsx-a11y: 6.10.2
  eslint-plugin-perfectionist: 5.3.0
  eslint-plugin-react: 7.37.5
  eslint-plugin-react-hooks: 7.0.1
  globals: 17.0.0
  id128: 1.6.6
  jiti: 2.6.1
  nx: 22.4.2
  prettier: 3.7.4
  react: 19.2.3
  react-aria: 3.45.0
  react-aria-components: 1.14.0
  react-dom: 19.2.3
  react-error-boundary: 6.0.2
  react-icons: 5.5.0
  react-markdown: 10.1.0
  react-resizable-panels: 4.3.0
  react-scan: 0.4.3
  react-stately: 3.43.0
  react-timeago: 8.3.0
  storybook: 10.1.11
  swc-node: 1.0.0
  syncpack: 13.0.4
  tailwind-merge: 3.4.0
  tailwind-variants: 3.2.2
  tailwindcss: 4.1.18
  tailwindcss-react-aria-components: 2.0.1
  ts-node: 10.9.2
  tsup: 8.5.1
  tw-animate-css: 1.4.0
  typescript: 5.9.3
  typescript-eslint: 8.52.0
  undici: 7.18.2
  use-debounce: 10.0.6
  vite: 7.3.1
  vite-tsconfig-paths: 6.0.3
  vitest: 3.1.4
  yaml: 2.8.2

catalogMode: strict

cleanupUnusedCatalogs: true

onlyBuiltDependencies:
  - '@bufbuild/buf'
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - bufferutil
  - electron
  - electron-winstaller
  - es5-ext
  - esbuild
  - keccak
  - lmdb
  - msgpackr-extract
  - nx
  - oxc-resolver
  - secp256k1
  - sharp
  - unrs-resolver
  - utf-8-validate

overrides:
  '@types/eslint': '-'

patchedDependencies:
  '@effect/platform-node-shared': patches/@effect__platform-node-shared.patch
  '@nx/eslint': patches/@nx__eslint.patch
  '@react-stately/table': patches/@react-stately__table.patch

packageExtensions:
  better-auth:
    dependencies:
      drizzle-orm: '*'

savePrefix: ''
