# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

includes:
  design-tokens:
    taskfile: ./src/design-tokens
    aliases: [design]

tasks:
  default:
    desc: List all available development commands
    cmd: task --list-all --sort=none

  dev:
    desc: >-
      Start the development server, see for more info:
      https://docs.plasmo.com/framework/workflows/dev
    cmd: pnpm plasmo dev

  build:
    desc: Create a production build
    cmd: pnpm plasmo build --zip

  lint:
    desc: Verify code conventions
    cmds:
      # Consider switching to Commitizen and using a Commit Message File to run the check inside of a Nix derivation
      # https://commitizen-tools.github.io/commitizen/commands/check/#commit-message-file
      - '{{if ne .COG "false"}} cog check {{end}}'
      - pnpm prettier --check .
      - pnpm eslint .
