# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

includes:
  design-tokens:
    taskfile: ./src/design-tokens
    aliases: [design]

tasks:
  default:
    desc: List all available development commands
    cmd: task --list-all --sort=none

  dev:
    desc: >-
      Start the development server, see for more info:
      https://docs.plasmo.com/framework/workflows/dev
    cmd: pnpm plasmo dev

  build:
    desc: Create a production build
    cmd: pnpm plasmo build --zip

  lint:
    desc: Verify code conventions
    cmds:
      - cog check
      - pnpm prettier --check .
      - pnpm eslint .
