# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  build:
    desc: Generate everything
    cmds:
      - task: build:typespec
      - task: build:step-2

  build:step-2:
    internal: true
    deps:
      - build:buf
      # - build:quicktype:effect

  build:typespec:
    desc: Use TypeSpec to generate Protobuf and JSON Schema
    cmd: pnpm tsp compile api
    sources: [api/**/*]
    generates: [dist/@typespec/**/*]

  build:buf:
    desc: Use Buf to generate TypeScript and Go code for ConnectRPC
    deps: [build:typespec]
    sources: [dist/@typespec/protobuf/**/*]
    generates: ['dist/@buf/**/*']
    cmd: pnpm buf generate

  build:quicktype:effect:
    desc: Use Quicktype to generate Effect Schema
    deps: [build:typespec]
    sources: [dist/@typespec/json-schema/**/*]
    generates: ['dist/@quicktype/effect-schema.ts']
    cmds:
      - mkdir -p ./dist/@quicktype
      - >-
        pnpm quicktype \
          --src-lang=schema \
          --lang=typescript-effect-schema \
          --out ./dist/@quicktype/effect-schema.ts \
          ./dist/@typespec/json-schema/*

  lint:
    desc: Lint Protobuf code generated by TypeSpec
    deps: [build:typespec]
    cmd: pnpm buf lint

  clean:
    desc: Cleanup build files
    cmd: rm -rf .task dist
