# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

includes:
  design-tokens:
    taskfile: ./src/design-tokens
    aliases: [design]

tasks:
  default: task --list-all
  dev: pnpm plasmo dev
  build: pnpm plasmo build
  package: pnpm plasmo package
  lint:
    - pnpm prettier --check .
    - pnpm eslint .
