output-dir: '{project-root}/dist'

emit:
  - '@typespec/protobuf'
  - '@typespec/json-schema'

options:
  '@typespec/json-schema':
    file-type: json
    emitAllModels: true

linter:
  extends:
    - '@typespec/best-practices/recommended'
