[tool.sqlfluff.core]
dialect = "sqlite"
output_line_length = 120 
processes = -1
exclude_rules = "L051,L031"


[tool.sqlfluff.indentation]
tab_space_size = 4
max_line_length = 120
indent_unit = "space"
allow_scalar = true
single_table_references = "consistent"
unquoted_identifiers_policy = "all"

