# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  from-tailwind:
    aliases: [from-tw]
    desc: >-
      Generate Tailwind design tokens for Token Studio. The result will be
      available at ./src/design-tokens/tokens.json
    cmd: pnpm tsx ./src/design-tokens/from-tailwind
