output-dir: '{project-root}/dist'

emit:
  - '@typespec/protobuf'
  - '@typespec/json-schema'
  - ../lib/emitter.js
# options:
#   '@typespec/json-schema':
#     file-type: json
#     emitAllModels: true
