/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './root';
import { Route as loginImport } from './login';
import { Route as authorizedImport } from './authorized';
import { Route as dashboardImport } from './dashboard';
import { Route as workspaceLayoutImport } from './workspace/layout';
import { Route as workspaceListImport } from './workspace/list';
import { Route as workspaceMembersImport } from './workspace/members';
import { Route as workspaceOverviewImport } from './workspace/overview';
import { Route as flowLayoutImport } from './flow/layout';
import { Route as flowHistoryImport } from './flow/history';
import { Route as flowFlowImport } from './flow/flow';
import { Route as endpointImport } from './endpoint';

// Create/Update Routes

const loginRoute = loginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any);

const authorizedRoute = authorizedImport.update({
  id: '/_authorized',
  getParentRoute: () => rootRoute,
} as any);

const dashboardRoute = dashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => authorizedRoute,
} as any);

const workspaceLayoutRoute = workspaceLayoutImport.update({
  id: '/workspace/$workspaceIdCan',
  path: '/workspace/$workspaceIdCan',
  getParentRoute: () => authorizedRoute,
} as any);

const workspaceListRoute = workspaceListImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardRoute,
} as any);

const workspaceMembersRoute = workspaceMembersImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => workspaceLayoutRoute,
} as any);

const workspaceOverviewRoute = workspaceOverviewImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => workspaceLayoutRoute,
} as any);

const flowLayoutRoute = flowLayoutImport.update({
  id: '/flow/$flowIdCan',
  path: '/flow/$flowIdCan',
  getParentRoute: () => workspaceLayoutRoute,
} as any);

const flowHistoryRoute = flowHistoryImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => flowLayoutRoute,
} as any);

const flowFlowRoute = flowFlowImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => flowLayoutRoute,
} as any);

const endpointRoute = endpointImport.update({
  id: '/endpoint/$endpointIdCan/example/$exampleIdCan',
  path: '/endpoint/$endpointIdCan/example/$exampleIdCan',
  getParentRoute: () => workspaceLayoutRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authorized': {
      id: '/_authorized';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof authorizedImport;
      parentRoute: typeof rootRoute;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof loginImport;
      parentRoute: typeof rootRoute;
    };
    '/_authorized/_dashboard': {
      id: '/_authorized/_dashboard';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof dashboardImport;
      parentRoute: typeof authorizedImport;
    };
    '/_authorized/_dashboard/': {
      id: '/_authorized/_dashboard/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof workspaceListImport;
      parentRoute: typeof dashboardImport;
    };
    '/_authorized/workspace/$workspaceIdCan': {
      id: '/_authorized/workspace/$workspaceIdCan';
      path: '/workspace/$workspaceIdCan';
      fullPath: '/workspace/$workspaceIdCan';
      preLoaderRoute: typeof workspaceLayoutImport;
      parentRoute: typeof authorizedImport;
    };
    '/_authorized/workspace/$workspaceIdCan/': {
      id: '/_authorized/workspace/$workspaceIdCan/';
      path: '/';
      fullPath: '/workspace/$workspaceIdCan/';
      preLoaderRoute: typeof workspaceOverviewImport;
      parentRoute: typeof workspaceLayoutImport;
    };
    '/_authorized/workspace/$workspaceIdCan/members': {
      id: '/_authorized/workspace/$workspaceIdCan/members';
      path: '/members';
      fullPath: '/workspace/$workspaceIdCan/members';
      preLoaderRoute: typeof workspaceMembersImport;
      parentRoute: typeof workspaceLayoutImport;
    };
    '/_authorized/workspace/$workspaceIdCan/flow/$flowIdCan': {
      id: '/_authorized/workspace/$workspaceIdCan/flow/$flowIdCan';
      path: '/flow/$flowIdCan';
      fullPath: '/workspace/$workspaceIdCan/flow/$flowIdCan';
      preLoaderRoute: typeof flowLayoutImport;
      parentRoute: typeof workspaceLayoutImport;
    };
    '/_authorized/workspace/$workspaceIdCan/flow/$flowIdCan/': {
      id: '/_authorized/workspace/$workspaceIdCan/flow/$flowIdCan/';
      path: '/';
      fullPath: '/workspace/$workspaceIdCan/flow/$flowIdCan/';
      preLoaderRoute: typeof flowFlowImport;
      parentRoute: typeof flowLayoutImport;
    };
    '/_authorized/workspace/$workspaceIdCan/flow/$flowIdCan/history': {
      id: '/_authorized/workspace/$workspaceIdCan/flow/$flowIdCan/history';
      path: '/history';
      fullPath: '/workspace/$workspaceIdCan/flow/$flowIdCan/history';
      preLoaderRoute: typeof flowHistoryImport;
      parentRoute: typeof flowLayoutImport;
    };
    '/_authorized/workspace/$workspaceIdCan/endpoint/$endpointIdCan/example/$exampleIdCan': {
      id: '/_authorized/workspace/$workspaceIdCan/endpoint/$endpointIdCan/example/$exampleIdCan';
      path: '/endpoint/$endpointIdCan/example/$exampleIdCan';
      fullPath: '/workspace/$workspaceIdCan/endpoint/$endpointIdCan/example/$exampleIdCan';
      preLoaderRoute: typeof endpointImport;
      parentRoute: typeof workspaceLayoutImport;
    };
  }
}

// Create and export the route tree

interface dashboardRouteChildren {
  workspaceListRoute: typeof workspaceListRoute;
}

const dashboardRouteChildren: dashboardRouteChildren = {
  workspaceListRoute: workspaceListRoute,
};

const dashboardRouteWithChildren = dashboardRoute._addFileChildren(
  dashboardRouteChildren,
);

interface flowLayoutRouteChildren {
  flowFlowRoute: typeof flowFlowRoute;
  flowHistoryRoute: typeof flowHistoryRoute;
}

const flowLayoutRouteChildren: flowLayoutRouteChildren = {
  flowFlowRoute: flowFlowRoute,
  flowHistoryRoute: flowHistoryRoute,
};

const flowLayoutRouteWithChildren = flowLayoutRoute._addFileChildren(
  flowLayoutRouteChildren,
);

interface workspaceLayoutRouteChildren {
  workspaceOverviewRoute: typeof workspaceOverviewRoute;
  workspaceMembersRoute: typeof workspaceMembersRoute;
  flowLayoutRoute: typeof flowLayoutRouteWithChildren;
  endpointRoute: typeof endpointRoute;
}

const workspaceLayoutRouteChildren: workspaceLayoutRouteChildren = {
  workspaceOverviewRoute: workspaceOverviewRoute,
  workspaceMembersRoute: workspaceMembersRoute,
  flowLayoutRoute: flowLayoutRouteWithChildren,
  endpointRoute: endpointRoute,
};

const workspaceLayoutRouteWithChildren = workspaceLayoutRoute._addFileChildren(
  workspaceLayoutRouteChildren,
);

interface authorizedRouteChildren {
  dashboardRoute: typeof dashboardRouteWithChildren;
  workspaceLayoutRoute: typeof workspaceLayoutRouteWithChildren;
}

const authorizedRouteChildren: authorizedRouteChildren = {
  dashboardRoute: dashboardRouteWithChildren,
  workspaceLayoutRoute: workspaceLayoutRouteWithChildren,
};

const authorizedRouteWithChildren = authorizedRoute._addFileChildren(
  authorizedRouteChildren,
);

export interface FileRoutesByFullPath {
  '': typeof dashboardRouteWithChildren;
  '/login': typeof loginRoute;
  '/': typeof workspaceListRoute;
  '/workspace/$workspaceIdCan': typeof workspaceLayoutRouteWithChildren;
  '/workspace/$workspaceIdCan/': typeof workspaceOverviewRoute;
  '/workspace/$workspaceIdCan/members': typeof workspaceMembersRoute;
  '/workspace/$workspaceIdCan/flow/$flowIdCan': typeof flowLayoutRouteWithChildren;
  '/workspace/$workspaceIdCan/flow/$flowIdCan/': typeof flowFlowRoute;
  '/workspace/$workspaceIdCan/flow/$flowIdCan/history': typeof flowHistoryRoute;
  '/workspace/$workspaceIdCan/endpoint/$endpointIdCan/example/$exampleIdCan': typeof endpointRoute;
}

export interface FileRoutesByTo {
  '': typeof authorizedRouteWithChildren;
  '/login': typeof loginRoute;
  '/': typeof workspaceListRoute;
  '/workspace/$workspaceIdCan': typeof workspaceOverviewRoute;
  '/workspace/$workspaceIdCan/members': typeof workspaceMembersRoute;
  '/workspace/$workspaceIdCan/flow/$flowIdCan': typeof flowFlowRoute;
  '/workspace/$workspaceIdCan/flow/$flowIdCan/history': typeof flowHistoryRoute;
  '/workspace/$workspaceIdCan/endpoint/$endpointIdCan/example/$exampleIdCan': typeof endpointRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/_authorized': typeof authorizedRouteWithChildren;
  '/login': typeof loginRoute;
  '/_authorized/_dashboard': typeof dashboardRouteWithChildren;
  '/_authorized/_dashboard/': typeof workspaceListRoute;
  '/_authorized/workspace/$workspaceIdCan': typeof workspaceLayoutRouteWithChildren;
  '/_authorized/workspace/$workspaceIdCan/': typeof workspaceOverviewRoute;
  '/_authorized/workspace/$workspaceIdCan/members': typeof workspaceMembersRoute;
  '/_authorized/workspace/$workspaceIdCan/flow/$flowIdCan': typeof flowLayoutRouteWithChildren;
  '/_authorized/workspace/$workspaceIdCan/flow/$flowIdCan/': typeof flowFlowRoute;
  '/_authorized/workspace/$workspaceIdCan/flow/$flowIdCan/history': typeof flowHistoryRoute;
  '/_authorized/workspace/$workspaceIdCan/endpoint/$endpointIdCan/example/$exampleIdCan': typeof endpointRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | ''
    | '/login'
    | '/'
    | '/workspace/$workspaceIdCan'
    | '/workspace/$workspaceIdCan/'
    | '/workspace/$workspaceIdCan/members'
    | '/workspace/$workspaceIdCan/flow/$flowIdCan'
    | '/workspace/$workspaceIdCan/flow/$flowIdCan/'
    | '/workspace/$workspaceIdCan/flow/$flowIdCan/history'
    | '/workspace/$workspaceIdCan/endpoint/$endpointIdCan/example/$exampleIdCan';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | ''
    | '/login'
    | '/'
    | '/workspace/$workspaceIdCan'
    | '/workspace/$workspaceIdCan/members'
    | '/workspace/$workspaceIdCan/flow/$flowIdCan'
    | '/workspace/$workspaceIdCan/flow/$flowIdCan/history'
    | '/workspace/$workspaceIdCan/endpoint/$endpointIdCan/example/$exampleIdCan';
  id:
    | '__root__'
    | '/_authorized'
    | '/login'
    | '/_authorized/_dashboard'
    | '/_authorized/_dashboard/'
    | '/_authorized/workspace/$workspaceIdCan'
    | '/_authorized/workspace/$workspaceIdCan/'
    | '/_authorized/workspace/$workspaceIdCan/members'
    | '/_authorized/workspace/$workspaceIdCan/flow/$flowIdCan'
    | '/_authorized/workspace/$workspaceIdCan/flow/$flowIdCan/'
    | '/_authorized/workspace/$workspaceIdCan/flow/$flowIdCan/history'
    | '/_authorized/workspace/$workspaceIdCan/endpoint/$endpointIdCan/example/$exampleIdCan';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  authorizedRoute: typeof authorizedRouteWithChildren;
  loginRoute: typeof loginRoute;
}

const rootRouteChildren: RootRouteChildren = {
  authorizedRoute: authorizedRouteWithChildren,
  loginRoute: loginRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "root.tsx",
      "children": [
        "/_authorized",
        "/login"
      ]
    },
    "/_authorized": {
      "filePath": "authorized.tsx",
      "children": [
        "/_authorized/_dashboard",
        "/_authorized/workspace/$workspaceIdCan"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_authorized/_dashboard": {
      "filePath": "dashboard.tsx",
      "parent": "/_authorized",
      "children": [
        "/_authorized/_dashboard/"
      ]
    },
    "/_authorized/_dashboard/": {
      "filePath": "workspace/list.tsx",
      "parent": "/_authorized/_dashboard"
    },
    "/_authorized/workspace/$workspaceIdCan": {
      "filePath": "workspace/layout.tsx",
      "parent": "/_authorized",
      "children": [
        "/_authorized/workspace/$workspaceIdCan/",
        "/_authorized/workspace/$workspaceIdCan/members",
        "/_authorized/workspace/$workspaceIdCan/flow/$flowIdCan",
        "/_authorized/workspace/$workspaceIdCan/endpoint/$endpointIdCan/example/$exampleIdCan"
      ]
    },
    "/_authorized/workspace/$workspaceIdCan/": {
      "filePath": "workspace/overview.tsx",
      "parent": "/_authorized/workspace/$workspaceIdCan"
    },
    "/_authorized/workspace/$workspaceIdCan/members": {
      "filePath": "workspace/members.tsx",
      "parent": "/_authorized/workspace/$workspaceIdCan"
    },
    "/_authorized/workspace/$workspaceIdCan/flow/$flowIdCan": {
      "filePath": "flow/layout.tsx",
      "parent": "/_authorized/workspace/$workspaceIdCan",
      "children": [
        "/_authorized/workspace/$workspaceIdCan/flow/$flowIdCan/",
        "/_authorized/workspace/$workspaceIdCan/flow/$flowIdCan/history"
      ]
    },
    "/_authorized/workspace/$workspaceIdCan/flow/$flowIdCan/": {
      "filePath": "flow/flow.tsx",
      "parent": "/_authorized/workspace/$workspaceIdCan/flow/$flowIdCan"
    },
    "/_authorized/workspace/$workspaceIdCan/flow/$flowIdCan/history": {
      "filePath": "flow/history.tsx",
      "parent": "/_authorized/workspace/$workspaceIdCan/flow/$flowIdCan"
    },
    "/_authorized/workspace/$workspaceIdCan/endpoint/$endpointIdCan/example/$exampleIdCan": {
      "filePath": "endpoint.tsx",
      "parent": "/_authorized/workspace/$workspaceIdCan"
    }
  }
}
ROUTE_MANIFEST_END */
