// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v5.27.2
// source: protos/node.proto

package nodepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SingleNodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeID string `protobuf:"bytes,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	Data   []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SingleNodeRequest) Reset() {
	*x = SingleNodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_node_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleNodeRequest) ProtoMessage() {}

func (x *SingleNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_node_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleNodeRequest.ProtoReflect.Descriptor instead.
func (*SingleNodeRequest) Descriptor() ([]byte, []int) {
	return file_protos_node_proto_rawDescGZIP(), []int{0}
}

func (x *SingleNodeRequest) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

func (x *SingleNodeRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SingleNodeRespond struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NextNodeID string `protobuf:"bytes,1,opt,name=nextNodeID,proto3" json:"nextNodeID,omitempty"`
	Data       []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SingleNodeRespond) Reset() {
	*x = SingleNodeRespond{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_node_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleNodeRespond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleNodeRespond) ProtoMessage() {}

func (x *SingleNodeRespond) ProtoReflect() protoreflect.Message {
	mi := &file_protos_node_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleNodeRespond.ProtoReflect.Descriptor instead.
func (*SingleNodeRespond) Descriptor() ([]byte, []int) {
	return file_protos_node_proto_rawDescGZIP(), []int{1}
}

func (x *SingleNodeRespond) GetNextNodeID() string {
	if x != nil {
		return x.NextNodeID
	}
	return ""
}

func (x *SingleNodeRespond) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type MultiNodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeID     string `protobuf:"bytes,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	StopNodeID string `protobuf:"bytes,2,opt,name=stopNodeID,proto3" json:"stopNodeID,omitempty"`
	Data       []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *MultiNodeRequest) Reset() {
	*x = MultiNodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_node_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiNodeRequest) ProtoMessage() {}

func (x *MultiNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_node_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiNodeRequest.ProtoReflect.Descriptor instead.
func (*MultiNodeRequest) Descriptor() ([]byte, []int) {
	return file_protos_node_proto_rawDescGZIP(), []int{2}
}

func (x *MultiNodeRequest) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

func (x *MultiNodeRequest) GetStopNodeID() string {
	if x != nil {
		return x.StopNodeID
	}
	return ""
}

func (x *MultiNodeRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type MultiNodeStatusStream struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeID string `protobuf:"bytes,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	Data   []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *MultiNodeStatusStream) Reset() {
	*x = MultiNodeStatusStream{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_node_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiNodeStatusStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiNodeStatusStream) ProtoMessage() {}

func (x *MultiNodeStatusStream) ProtoReflect() protoreflect.Message {
	mi := &file_protos_node_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiNodeStatusStream.ProtoReflect.Descriptor instead.
func (*MultiNodeStatusStream) Descriptor() ([]byte, []int) {
	return file_protos_node_proto_rawDescGZIP(), []int{3}
}

func (x *MultiNodeStatusStream) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

func (x *MultiNodeStatusStream) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_protos_node_proto protoreflect.FileDescriptor

var file_protos_node_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3f,
	0x0a, 0x11, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x47, 0x0a, 0x11, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x65, 0x78, 0x74, 0x4e, 0x6f, 0x64, 0x65,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x65, 0x78, 0x74, 0x4e, 0x6f,
	0x64, 0x65, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x5e, 0x0a, 0x10, 0x4d, 0x75, 0x6c, 0x74,
	0x69, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x6e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f,
	0x64, 0x65, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x6f, 0x70, 0x4e, 0x6f, 0x64, 0x65,
	0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x74, 0x6f, 0x70, 0x4e, 0x6f,
	0x64, 0x65, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x43, 0x0a, 0x15, 0x4d, 0x75, 0x6c, 0x74,
	0x69, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x9d, 0x01,
	0x0a, 0x0b, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a,
	0x03, 0x52, 0x75, 0x6e, 0x12, 0x1c, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53,
	0x69, 0x6e, 0x67, 0x6c, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64,
	0x12, 0x4b, 0x0a, 0x08, 0x52, 0x75, 0x6e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x12, 0x1b, 0x2e, 0x6e,
	0x6f, 0x64, 0x65, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x4e, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x6e, 0x6f, 0x64, 0x65,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x4e, 0x6f, 0x64, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x30, 0x01, 0x42, 0x0a, 0x5a,
	0x08, 0x2e, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_protos_node_proto_rawDescOnce sync.Once
	file_protos_node_proto_rawDescData = file_protos_node_proto_rawDesc
)

func file_protos_node_proto_rawDescGZIP() []byte {
	file_protos_node_proto_rawDescOnce.Do(func() {
		file_protos_node_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_node_proto_rawDescData)
	})
	return file_protos_node_proto_rawDescData
}

var file_protos_node_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_node_proto_goTypes = []interface{}{
	(*SingleNodeRequest)(nil),     // 0: nodeproto.SingleNodeRequest
	(*SingleNodeRespond)(nil),     // 1: nodeproto.SingleNodeRespond
	(*MultiNodeRequest)(nil),      // 2: nodeproto.MultiNodeRequest
	(*MultiNodeStatusStream)(nil), // 3: nodeproto.MultiNodeStatusStream
}
var file_protos_node_proto_depIdxs = []int32{
	0, // 0: nodeproto.NodeService.Run:input_type -> nodeproto.SingleNodeRequest
	2, // 1: nodeproto.NodeService.RunMulti:input_type -> nodeproto.MultiNodeRequest
	1, // 2: nodeproto.NodeService.Run:output_type -> nodeproto.SingleNodeRespond
	3, // 3: nodeproto.NodeService.RunMulti:output_type -> nodeproto.MultiNodeStatusStream
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_node_proto_init() }
func file_protos_node_proto_init() {
	if File_protos_node_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_node_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingleNodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_node_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingleNodeRespond); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_node_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiNodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_node_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiNodeStatusStream); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_node_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_node_proto_goTypes,
		DependencyIndexes: file_protos_node_proto_depIdxs,
		MessageInfos:      file_protos_node_proto_msgTypes,
	}.Build()
	File_protos_node_proto = out.File
	file_protos_node_proto_rawDesc = nil
	file_protos_node_proto_goTypes = nil
	file_protos_node_proto_depIdxs = nil
}
