/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './root';
import { Route as loginImport } from './login';
import { Route as authorizedImport } from './authorized';
import { Route as dashboardImport } from './dashboard';
import { Route as workspaceLayoutImport } from './workspace-layout';
import { Route as workspaceListImport } from './workspace-list';
import { Route as workspaceMembersImport } from './workspace-members';
import { Route as apiCallImport } from './api-call';
import { Route as headersImport } from './headers';
import { Route as bodyImport } from './body';
import { Route as queryImport } from './query';

// Create/Update Routes

const loginRoute = loginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any);

const authorizedRoute = authorizedImport.update({
  id: '/_authorized',
  getParentRoute: () => rootRoute,
} as any);

const dashboardRoute = dashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => authorizedRoute,
} as any);

const workspaceLayoutRoute = workspaceLayoutImport.update({
  path: '/workspace/$workspaceId',
  getParentRoute: () => authorizedRoute,
} as any);

const workspaceListRoute = workspaceListImport.update({
  path: '/',
  getParentRoute: () => dashboardRoute,
} as any);

const workspaceMembersRoute = workspaceMembersImport.update({
  path: '/members',
  getParentRoute: () => workspaceLayoutRoute,
} as any);

const apiCallRoute = apiCallImport.update({
  path: '/api-call/$apiCallId/example/$exampleId',
  getParentRoute: () => workspaceLayoutRoute,
} as any);

const headersRoute = headersImport.update({
  path: '/headers',
  getParentRoute: () => apiCallRoute,
} as any);

const bodyRoute = bodyImport.update({
  path: '/body',
  getParentRoute: () => apiCallRoute,
} as any);

const queryRoute = queryImport.update({
  path: '/',
  getParentRoute: () => apiCallRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authorized': {
      id: '/_authorized';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof authorizedImport;
      parentRoute: typeof rootRoute;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof loginImport;
      parentRoute: typeof rootRoute;
    };
    '/_authorized/_dashboard': {
      id: '/_authorized/_dashboard';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof dashboardImport;
      parentRoute: typeof authorizedImport;
    };
    '/_authorized/_dashboard/': {
      id: '/_authorized/_dashboard/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof workspaceListImport;
      parentRoute: typeof dashboardImport;
    };
    '/_authorized/workspace/$workspaceId': {
      id: '/_authorized/workspace/$workspaceId';
      path: '/workspace/$workspaceId';
      fullPath: '/workspace/$workspaceId';
      preLoaderRoute: typeof workspaceLayoutImport;
      parentRoute: typeof authorizedImport;
    };
    '/_authorized/workspace/$workspaceId/members': {
      id: '/_authorized/workspace/$workspaceId/members';
      path: '/members';
      fullPath: '/workspace/$workspaceId/members';
      preLoaderRoute: typeof workspaceMembersImport;
      parentRoute: typeof workspaceLayoutImport;
    };
    '/_authorized/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId': {
      id: '/_authorized/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId';
      path: '/api-call/$apiCallId/example/$exampleId';
      fullPath: '/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId';
      preLoaderRoute: typeof apiCallImport;
      parentRoute: typeof workspaceLayoutImport;
    };
    '/_authorized/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId/': {
      id: '/_authorized/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId/';
      path: '/';
      fullPath: '/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId/';
      preLoaderRoute: typeof queryImport;
      parentRoute: typeof apiCallImport;
    };
    '/_authorized/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId/body': {
      id: '/_authorized/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId/body';
      path: '/body';
      fullPath: '/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId/body';
      preLoaderRoute: typeof bodyImport;
      parentRoute: typeof apiCallImport;
    };
    '/_authorized/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId/headers': {
      id: '/_authorized/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId/headers';
      path: '/headers';
      fullPath: '/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId/headers';
      preLoaderRoute: typeof headersImport;
      parentRoute: typeof apiCallImport;
    };
  }
}

// Create and export the route tree

interface dashboardRouteChildren {
  workspaceListRoute: typeof workspaceListRoute;
}

const dashboardRouteChildren: dashboardRouteChildren = {
  workspaceListRoute: workspaceListRoute,
};

const dashboardRouteWithChildren = dashboardRoute._addFileChildren(
  dashboardRouteChildren,
);

interface apiCallRouteChildren {
  queryRoute: typeof queryRoute;
  bodyRoute: typeof bodyRoute;
  headersRoute: typeof headersRoute;
}

const apiCallRouteChildren: apiCallRouteChildren = {
  queryRoute: queryRoute,
  bodyRoute: bodyRoute,
  headersRoute: headersRoute,
};

const apiCallRouteWithChildren =
  apiCallRoute._addFileChildren(apiCallRouteChildren);

interface workspaceLayoutRouteChildren {
  workspaceMembersRoute: typeof workspaceMembersRoute;
  apiCallRoute: typeof apiCallRouteWithChildren;
}

const workspaceLayoutRouteChildren: workspaceLayoutRouteChildren = {
  workspaceMembersRoute: workspaceMembersRoute,
  apiCallRoute: apiCallRouteWithChildren,
};

const workspaceLayoutRouteWithChildren = workspaceLayoutRoute._addFileChildren(
  workspaceLayoutRouteChildren,
);

interface authorizedRouteChildren {
  dashboardRoute: typeof dashboardRouteWithChildren;
  workspaceLayoutRoute: typeof workspaceLayoutRouteWithChildren;
}

const authorizedRouteChildren: authorizedRouteChildren = {
  dashboardRoute: dashboardRouteWithChildren,
  workspaceLayoutRoute: workspaceLayoutRouteWithChildren,
};

const authorizedRouteWithChildren = authorizedRoute._addFileChildren(
  authorizedRouteChildren,
);

export interface FileRoutesByFullPath {
  '': typeof dashboardRouteWithChildren;
  '/login': typeof loginRoute;
  '/': typeof workspaceListRoute;
  '/workspace/$workspaceId': typeof workspaceLayoutRouteWithChildren;
  '/workspace/$workspaceId/members': typeof workspaceMembersRoute;
  '/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId': typeof apiCallRouteWithChildren;
  '/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId/': typeof queryRoute;
  '/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId/body': typeof bodyRoute;
  '/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId/headers': typeof headersRoute;
}

export interface FileRoutesByTo {
  '': typeof authorizedRouteWithChildren;
  '/login': typeof loginRoute;
  '/': typeof workspaceListRoute;
  '/workspace/$workspaceId': typeof workspaceLayoutRouteWithChildren;
  '/workspace/$workspaceId/members': typeof workspaceMembersRoute;
  '/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId': typeof queryRoute;
  '/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId/body': typeof bodyRoute;
  '/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId/headers': typeof headersRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/_authorized': typeof authorizedRouteWithChildren;
  '/login': typeof loginRoute;
  '/_authorized/_dashboard': typeof dashboardRouteWithChildren;
  '/_authorized/_dashboard/': typeof workspaceListRoute;
  '/_authorized/workspace/$workspaceId': typeof workspaceLayoutRouteWithChildren;
  '/_authorized/workspace/$workspaceId/members': typeof workspaceMembersRoute;
  '/_authorized/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId': typeof apiCallRouteWithChildren;
  '/_authorized/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId/': typeof queryRoute;
  '/_authorized/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId/body': typeof bodyRoute;
  '/_authorized/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId/headers': typeof headersRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | ''
    | '/login'
    | '/'
    | '/workspace/$workspaceId'
    | '/workspace/$workspaceId/members'
    | '/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId'
    | '/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId/'
    | '/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId/body'
    | '/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId/headers';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | ''
    | '/login'
    | '/'
    | '/workspace/$workspaceId'
    | '/workspace/$workspaceId/members'
    | '/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId'
    | '/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId/body'
    | '/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId/headers';
  id:
    | '__root__'
    | '/_authorized'
    | '/login'
    | '/_authorized/_dashboard'
    | '/_authorized/_dashboard/'
    | '/_authorized/workspace/$workspaceId'
    | '/_authorized/workspace/$workspaceId/members'
    | '/_authorized/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId'
    | '/_authorized/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId/'
    | '/_authorized/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId/body'
    | '/_authorized/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId/headers';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  authorizedRoute: typeof authorizedRouteWithChildren;
  loginRoute: typeof loginRoute;
}

const rootRouteChildren: RootRouteChildren = {
  authorizedRoute: authorizedRouteWithChildren,
  loginRoute: loginRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "root.tsx",
      "children": [
        "/_authorized",
        "/login"
      ]
    },
    "/_authorized": {
      "filePath": "authorized.tsx",
      "children": [
        "/_authorized/_dashboard",
        "/_authorized/workspace/$workspaceId"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_authorized/_dashboard": {
      "filePath": "dashboard.tsx",
      "parent": "/_authorized",
      "children": [
        "/_authorized/_dashboard/"
      ]
    },
    "/_authorized/_dashboard/": {
      "filePath": "workspace-list.tsx",
      "parent": "/_authorized/_dashboard"
    },
    "/_authorized/workspace/$workspaceId": {
      "filePath": "workspace-layout.tsx",
      "parent": "/_authorized",
      "children": [
        "/_authorized/workspace/$workspaceId/members",
        "/_authorized/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId"
      ]
    },
    "/_authorized/workspace/$workspaceId/members": {
      "filePath": "workspace-members.tsx",
      "parent": "/_authorized/workspace/$workspaceId"
    },
    "/_authorized/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId": {
      "filePath": "api-call.tsx",
      "parent": "/_authorized/workspace/$workspaceId",
      "children": [
        "/_authorized/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId/",
        "/_authorized/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId/body",
        "/_authorized/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId/headers"
      ]
    },
    "/_authorized/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId/": {
      "filePath": "query.tsx",
      "parent": "/_authorized/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId"
    },
    "/_authorized/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId/body": {
      "filePath": "body.tsx",
      "parent": "/_authorized/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId"
    },
    "/_authorized/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId/headers": {
      "filePath": "headers.tsx",
      "parent": "/_authorized/workspace/$workspaceId/api-call/$apiCallId/example/$exampleId"
    }
  }
}
ROUTE_MANIFEST_END */
