/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesIndexRouteImport } from './../../pages/dashboard/routes/index'
import { Route as dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotWorkspaceRoutesWorkspaceWorkspaceIdCanRouteRouteImport } from './../../pages/workspace/routes/workspace/$workspaceIdCan/route'
import { Route as dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotWorkspaceRoutesWorkspaceWorkspaceIdCanIndexRouteImport } from './../../pages/workspace/routes/workspace/$workspaceIdCan/index'
import { Route as dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanRouteRouteImport } from './../../pages/http/routes/http/$httpIdCan/route'
import { Route as dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanRouteRouteImport } from './../../pages/flow/routes/flow/$flowIdCan/route'
import { Route as dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanIndexRouteImport } from './../../pages/http/routes/http/$httpIdCan/index'
import { Route as dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanIndexRouteImport } from './../../pages/flow/routes/flow/$flowIdCan/index'
import { Route as dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotCredentialRoutesCredentialCredentialIdCanIndexRouteImport } from './../../pages/credential/routes/credential/$credentialIdCan/index'
import { Route as dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanHistoryRouteImport } from './../../pages/flow/routes/flow/$flowIdCan/history'
import { Route as dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanDeltaDotdeltaHttpIdCanRouteImport } from './../../pages/http/routes/http/$httpIdCan/delta.$deltaHttpIdCan'

const dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesIndexRoute =
  dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesIndexRouteImport.update(
    {
      id: '/(dashboard)/',
      path: '/',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotWorkspaceRoutesWorkspaceWorkspaceIdCanRouteRoute =
  dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotWorkspaceRoutesWorkspaceWorkspaceIdCanRouteRouteImport.update(
    {
      id: '/(dashboard)/(workspace)/workspace/$workspaceIdCan',
      path: '/workspace/$workspaceIdCan',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotWorkspaceRoutesWorkspaceWorkspaceIdCanIndexRoute =
  dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotWorkspaceRoutesWorkspaceWorkspaceIdCanIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotWorkspaceRoutesWorkspaceWorkspaceIdCanRouteRoute,
    } as any,
  )
const dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanRouteRoute =
  dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanRouteRouteImport.update(
    {
      id: '/(http)/http/$httpIdCan',
      path: '/http/$httpIdCan',
      getParentRoute: () =>
        dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotWorkspaceRoutesWorkspaceWorkspaceIdCanRouteRoute,
    } as any,
  )
const dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanRouteRoute =
  dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanRouteRouteImport.update(
    {
      id: '/(flow)/flow/$flowIdCan',
      path: '/flow/$flowIdCan',
      getParentRoute: () =>
        dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotWorkspaceRoutesWorkspaceWorkspaceIdCanRouteRoute,
    } as any,
  )
const dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanIndexRoute =
  dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanRouteRoute,
    } as any,
  )
const dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanIndexRoute =
  dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanRouteRoute,
    } as any,
  )
const dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotCredentialRoutesCredentialCredentialIdCanIndexRoute =
  dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotCredentialRoutesCredentialCredentialIdCanIndexRouteImport.update(
    {
      id: '/(credential)/credential/$credentialIdCan/',
      path: '/credential/$credentialIdCan/',
      getParentRoute: () =>
        dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotWorkspaceRoutesWorkspaceWorkspaceIdCanRouteRoute,
    } as any,
  )
const dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanHistoryRoute =
  dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanHistoryRouteImport.update(
    {
      id: '/history',
      path: '/history',
      getParentRoute: () =>
        dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanRouteRoute,
    } as any,
  )
const dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanDeltaDotdeltaHttpIdCanRoute =
  dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanDeltaDotdeltaHttpIdCanRouteImport.update(
    {
      id: '/delta/$deltaHttpIdCan',
      path: '/delta/$deltaHttpIdCan',
      getParentRoute: () =>
        dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesIndexRoute
  '/workspace/$workspaceIdCan': typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotWorkspaceRoutesWorkspaceWorkspaceIdCanRouteRouteWithChildren
  '/workspace/$workspaceIdCan/': typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotWorkspaceRoutesWorkspaceWorkspaceIdCanIndexRoute
  '/workspace/$workspaceIdCan/flow/$flowIdCan': typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanRouteRouteWithChildren
  '/workspace/$workspaceIdCan/http/$httpIdCan': typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanRouteRouteWithChildren
  '/workspace/$workspaceIdCan/flow/$flowIdCan/history': typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanHistoryRoute
  '/workspace/$workspaceIdCan/credential/$credentialIdCan': typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotCredentialRoutesCredentialCredentialIdCanIndexRoute
  '/workspace/$workspaceIdCan/flow/$flowIdCan/': typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanIndexRoute
  '/workspace/$workspaceIdCan/http/$httpIdCan/': typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanIndexRoute
  '/workspace/$workspaceIdCan/http/$httpIdCan/delta/$deltaHttpIdCan': typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanDeltaDotdeltaHttpIdCanRoute
}
export interface FileRoutesByTo {
  '/': typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesIndexRoute
  '/workspace/$workspaceIdCan': typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotWorkspaceRoutesWorkspaceWorkspaceIdCanIndexRoute
  '/workspace/$workspaceIdCan/flow/$flowIdCan/history': typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanHistoryRoute
  '/workspace/$workspaceIdCan/credential/$credentialIdCan': typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotCredentialRoutesCredentialCredentialIdCanIndexRoute
  '/workspace/$workspaceIdCan/flow/$flowIdCan': typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanIndexRoute
  '/workspace/$workspaceIdCan/http/$httpIdCan': typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanIndexRoute
  '/workspace/$workspaceIdCan/http/$httpIdCan/delta/$deltaHttpIdCan': typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanDeltaDotdeltaHttpIdCanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(dashboard)/': typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesIndexRoute
  '/(dashboard)/(workspace)/workspace/$workspaceIdCan': typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotWorkspaceRoutesWorkspaceWorkspaceIdCanRouteRouteWithChildren
  '/(dashboard)/(workspace)/workspace/$workspaceIdCan/': typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotWorkspaceRoutesWorkspaceWorkspaceIdCanIndexRoute
  '/(dashboard)/(workspace)/workspace/$workspaceIdCan/(flow)/flow/$flowIdCan': typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanRouteRouteWithChildren
  '/(dashboard)/(workspace)/workspace/$workspaceIdCan/(http)/http/$httpIdCan': typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanRouteRouteWithChildren
  '/(dashboard)/(workspace)/workspace/$workspaceIdCan/(flow)/flow/$flowIdCan/history': typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanHistoryRoute
  '/(dashboard)/(workspace)/workspace/$workspaceIdCan/(credential)/credential/$credentialIdCan/': typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotCredentialRoutesCredentialCredentialIdCanIndexRoute
  '/(dashboard)/(workspace)/workspace/$workspaceIdCan/(flow)/flow/$flowIdCan/': typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanIndexRoute
  '/(dashboard)/(workspace)/workspace/$workspaceIdCan/(http)/http/$httpIdCan/': typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanIndexRoute
  '/(dashboard)/(workspace)/workspace/$workspaceIdCan/(http)/http/$httpIdCan/delta/$deltaHttpIdCan': typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanDeltaDotdeltaHttpIdCanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/workspace/$workspaceIdCan'
    | '/workspace/$workspaceIdCan/'
    | '/workspace/$workspaceIdCan/flow/$flowIdCan'
    | '/workspace/$workspaceIdCan/http/$httpIdCan'
    | '/workspace/$workspaceIdCan/flow/$flowIdCan/history'
    | '/workspace/$workspaceIdCan/credential/$credentialIdCan'
    | '/workspace/$workspaceIdCan/flow/$flowIdCan/'
    | '/workspace/$workspaceIdCan/http/$httpIdCan/'
    | '/workspace/$workspaceIdCan/http/$httpIdCan/delta/$deltaHttpIdCan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/workspace/$workspaceIdCan'
    | '/workspace/$workspaceIdCan/flow/$flowIdCan/history'
    | '/workspace/$workspaceIdCan/credential/$credentialIdCan'
    | '/workspace/$workspaceIdCan/flow/$flowIdCan'
    | '/workspace/$workspaceIdCan/http/$httpIdCan'
    | '/workspace/$workspaceIdCan/http/$httpIdCan/delta/$deltaHttpIdCan'
  id:
    | '__root__'
    | '/(dashboard)/'
    | '/(dashboard)/(workspace)/workspace/$workspaceIdCan'
    | '/(dashboard)/(workspace)/workspace/$workspaceIdCan/'
    | '/(dashboard)/(workspace)/workspace/$workspaceIdCan/(flow)/flow/$flowIdCan'
    | '/(dashboard)/(workspace)/workspace/$workspaceIdCan/(http)/http/$httpIdCan'
    | '/(dashboard)/(workspace)/workspace/$workspaceIdCan/(flow)/flow/$flowIdCan/history'
    | '/(dashboard)/(workspace)/workspace/$workspaceIdCan/(credential)/credential/$credentialIdCan/'
    | '/(dashboard)/(workspace)/workspace/$workspaceIdCan/(flow)/flow/$flowIdCan/'
    | '/(dashboard)/(workspace)/workspace/$workspaceIdCan/(http)/http/$httpIdCan/'
    | '/(dashboard)/(workspace)/workspace/$workspaceIdCan/(http)/http/$httpIdCan/delta/$deltaHttpIdCan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesIndexRoute: typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesIndexRoute
  dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotWorkspaceRoutesWorkspaceWorkspaceIdCanRouteRoute: typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotWorkspaceRoutesWorkspaceWorkspaceIdCanRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(dashboard)/': {
      id: '/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/(workspace)/workspace/$workspaceIdCan': {
      id: '/(dashboard)/(workspace)/workspace/$workspaceIdCan'
      path: '/workspace/$workspaceIdCan'
      fullPath: '/workspace/$workspaceIdCan'
      preLoaderRoute: typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotWorkspaceRoutesWorkspaceWorkspaceIdCanRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/(workspace)/workspace/$workspaceIdCan/': {
      id: '/(dashboard)/(workspace)/workspace/$workspaceIdCan/'
      path: '/'
      fullPath: '/workspace/$workspaceIdCan/'
      preLoaderRoute: typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotWorkspaceRoutesWorkspaceWorkspaceIdCanIndexRouteImport
      parentRoute: typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotWorkspaceRoutesWorkspaceWorkspaceIdCanRouteRoute
    }
    '/(dashboard)/(workspace)/workspace/$workspaceIdCan/(http)/http/$httpIdCan': {
      id: '/(dashboard)/(workspace)/workspace/$workspaceIdCan/(http)/http/$httpIdCan'
      path: '/http/$httpIdCan'
      fullPath: '/workspace/$workspaceIdCan/http/$httpIdCan'
      preLoaderRoute: typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanRouteRouteImport
      parentRoute: typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotWorkspaceRoutesWorkspaceWorkspaceIdCanRouteRoute
    }
    '/(dashboard)/(workspace)/workspace/$workspaceIdCan/(flow)/flow/$flowIdCan': {
      id: '/(dashboard)/(workspace)/workspace/$workspaceIdCan/(flow)/flow/$flowIdCan'
      path: '/flow/$flowIdCan'
      fullPath: '/workspace/$workspaceIdCan/flow/$flowIdCan'
      preLoaderRoute: typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanRouteRouteImport
      parentRoute: typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotWorkspaceRoutesWorkspaceWorkspaceIdCanRouteRoute
    }
    '/(dashboard)/(workspace)/workspace/$workspaceIdCan/(http)/http/$httpIdCan/': {
      id: '/(dashboard)/(workspace)/workspace/$workspaceIdCan/(http)/http/$httpIdCan/'
      path: '/'
      fullPath: '/workspace/$workspaceIdCan/http/$httpIdCan/'
      preLoaderRoute: typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanIndexRouteImport
      parentRoute: typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanRouteRoute
    }
    '/(dashboard)/(workspace)/workspace/$workspaceIdCan/(flow)/flow/$flowIdCan/': {
      id: '/(dashboard)/(workspace)/workspace/$workspaceIdCan/(flow)/flow/$flowIdCan/'
      path: '/'
      fullPath: '/workspace/$workspaceIdCan/flow/$flowIdCan/'
      preLoaderRoute: typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanIndexRouteImport
      parentRoute: typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanRouteRoute
    }
    '/(dashboard)/(workspace)/workspace/$workspaceIdCan/(credential)/credential/$credentialIdCan/': {
      id: '/(dashboard)/(workspace)/workspace/$workspaceIdCan/(credential)/credential/$credentialIdCan/'
      path: '/credential/$credentialIdCan'
      fullPath: '/workspace/$workspaceIdCan/credential/$credentialIdCan'
      preLoaderRoute: typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotCredentialRoutesCredentialCredentialIdCanIndexRouteImport
      parentRoute: typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotWorkspaceRoutesWorkspaceWorkspaceIdCanRouteRoute
    }
    '/(dashboard)/(workspace)/workspace/$workspaceIdCan/(flow)/flow/$flowIdCan/history': {
      id: '/(dashboard)/(workspace)/workspace/$workspaceIdCan/(flow)/flow/$flowIdCan/history'
      path: '/history'
      fullPath: '/workspace/$workspaceIdCan/flow/$flowIdCan/history'
      preLoaderRoute: typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanHistoryRouteImport
      parentRoute: typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanRouteRoute
    }
    '/(dashboard)/(workspace)/workspace/$workspaceIdCan/(http)/http/$httpIdCan/delta/$deltaHttpIdCan': {
      id: '/(dashboard)/(workspace)/workspace/$workspaceIdCan/(http)/http/$httpIdCan/delta/$deltaHttpIdCan'
      path: '/delta/$deltaHttpIdCan'
      fullPath: '/workspace/$workspaceIdCan/http/$httpIdCan/delta/$deltaHttpIdCan'
      preLoaderRoute: typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanDeltaDotdeltaHttpIdCanRouteImport
      parentRoute: typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanRouteRoute
    }
  }
}

interface dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanRouteRouteChildren {
  dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanHistoryRoute: typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanHistoryRoute
  dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanIndexRoute: typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanIndexRoute
}

const dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanRouteRouteChildren: dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanRouteRouteChildren =
  {
    dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanHistoryRoute:
      dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanHistoryRoute,
    dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanIndexRoute:
      dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanIndexRoute,
  }

const dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanRouteRouteWithChildren =
  dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanRouteRoute._addFileChildren(
    dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanRouteRouteChildren,
  )

interface dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanRouteRouteChildren {
  dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanIndexRoute: typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanIndexRoute
  dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanDeltaDotdeltaHttpIdCanRoute: typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanDeltaDotdeltaHttpIdCanRoute
}

const dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanRouteRouteChildren: dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanRouteRouteChildren =
  {
    dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanIndexRoute:
      dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanIndexRoute,
    dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanDeltaDotdeltaHttpIdCanRoute:
      dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanDeltaDotdeltaHttpIdCanRoute,
  }

const dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanRouteRouteWithChildren =
  dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanRouteRoute._addFileChildren(
    dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanRouteRouteChildren,
  )

interface dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotWorkspaceRoutesWorkspaceWorkspaceIdCanRouteRouteChildren {
  dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotWorkspaceRoutesWorkspaceWorkspaceIdCanIndexRoute: typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotWorkspaceRoutesWorkspaceWorkspaceIdCanIndexRoute
  dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanRouteRoute: typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanRouteRouteWithChildren
  dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanRouteRoute: typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanRouteRouteWithChildren
  dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotCredentialRoutesCredentialCredentialIdCanIndexRoute: typeof dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotCredentialRoutesCredentialCredentialIdCanIndexRoute
}

const dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotWorkspaceRoutesWorkspaceWorkspaceIdCanRouteRouteChildren: dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotWorkspaceRoutesWorkspaceWorkspaceIdCanRouteRouteChildren =
  {
    dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotWorkspaceRoutesWorkspaceWorkspaceIdCanIndexRoute:
      dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotWorkspaceRoutesWorkspaceWorkspaceIdCanIndexRoute,
    dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanRouteRoute:
      dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotFlowRoutesFlowFlowIdCanRouteRouteWithChildren,
    dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanRouteRoute:
      dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotHttpRoutesHttpHttpIdCanRouteRouteWithChildren,
    dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotCredentialRoutesCredentialCredentialIdCanIndexRoute:
      dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotCredentialRoutesCredentialCredentialIdCanIndexRoute,
  }

const dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotWorkspaceRoutesWorkspaceWorkspaceIdCanRouteRouteWithChildren =
  dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotWorkspaceRoutesWorkspaceWorkspaceIdCanRouteRoute._addFileChildren(
    dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotWorkspaceRoutesWorkspaceWorkspaceIdCanRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesIndexRoute:
    dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesIndexRoute,
  dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotWorkspaceRoutesWorkspaceWorkspaceIdCanRouteRoute:
    dashboardDotDotChar92DotDotChar92DotDotChar92DotDotChar92pagesChar92dashboardChar92routesDotDotDotDotWorkspaceRoutesWorkspaceWorkspaceIdCanRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
