version: "2"

run:
  # Keep lint fast and focused for server package
  tests: false

linters:
  default: none
  enable:
    - govet
    - testifylint
    - importas
    - misspell
    - gosec
    - errorlint
    - bodyclose
    - noctx
    - gocritic
    - revive
    - errcheck
    - staticcheck
    - goconst
    - unused
    - unconvert
    - whitespace
    - sqlclosecheck
    - rowserrcheck
    - nilerr
    - makezero
    - wastedassign
    - ineffassign
    - durationcheck
    - nosprintfhostport
    - copyloopvar
    - exhaustive
    - intrange
  disable: []
  settings:
    importas:
      alias:
        - pkg: the-dev-tools/server/pkg/model/mhttp
          alias: mhttp
        - pkg: the-dev-tools/server/pkg/service/shttp
          alias: shttp
        - pkg: the-dev-tools/db/pkg/sqlc/gen
          alias: gen
    testifylint:
      enable-all: true
    revive:
      rules:
        - name: exported
          disabled: true
    exhaustive:
      # Treat 'default' case as covering all remaining cases
      default-signifies-exhaustive: true
      # Ignore protobuf UNSPECIFIED values and common Unknown patterns
      ignore-enum-members: ".*_UNSPECIFIED|.*Unknown|.*None"
      # Ignore stdlib types with many cases we don't need to handle exhaustively
      ignore-enum-types: "reflect.Kind"

issues:
  # Avoid noise from suggestions and test-only checks in this target
  exclude-rules:
    - linters:
        - revive
      text: "exported:"
