// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v5.27.2
// source: protos/flow.proto

package flowpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FlowCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *FlowCreateRequest) Reset() {
	*x = FlowCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_flow_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlowCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowCreateRequest) ProtoMessage() {}

func (x *FlowCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_flow_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowCreateRequest.ProtoReflect.Descriptor instead.
func (*FlowCreateRequest) Descriptor() ([]byte, []int) {
	return file_protos_flow_proto_rawDescGZIP(), []int{0}
}

func (x *FlowCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FlowSaveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *FlowSaveRequest) Reset() {
	*x = FlowSaveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_flow_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlowSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowSaveRequest) ProtoMessage() {}

func (x *FlowSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_flow_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowSaveRequest.ProtoReflect.Descriptor instead.
func (*FlowSaveRequest) Descriptor() ([]byte, []int) {
	return file_protos_flow_proto_rawDescGZIP(), []int{1}
}

func (x *FlowSaveRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FlowSaveRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FlowSaveRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type FlowLoadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *FlowLoadRequest) Reset() {
	*x = FlowLoadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_flow_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlowLoadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowLoadRequest) ProtoMessage() {}

func (x *FlowLoadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_flow_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowLoadRequest.ProtoReflect.Descriptor instead.
func (*FlowLoadRequest) Descriptor() ([]byte, []int) {
	return file_protos_flow_proto_rawDescGZIP(), []int{2}
}

func (x *FlowLoadRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FlowDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FlowDeleteRequest) Reset() {
	*x = FlowDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_flow_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlowDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowDeleteRequest) ProtoMessage() {}

func (x *FlowDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_flow_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowDeleteRequest.ProtoReflect.Descriptor instead.
func (*FlowDeleteRequest) Descriptor() ([]byte, []int) {
	return file_protos_flow_proto_rawDescGZIP(), []int{3}
}

func (x *FlowDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FlowCreateRespond struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FlowCreateRespond) Reset() {
	*x = FlowCreateRespond{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_flow_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlowCreateRespond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowCreateRespond) ProtoMessage() {}

func (x *FlowCreateRespond) ProtoReflect() protoreflect.Message {
	mi := &file_protos_flow_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowCreateRespond.ProtoReflect.Descriptor instead.
func (*FlowCreateRespond) Descriptor() ([]byte, []int) {
	return file_protos_flow_proto_rawDescGZIP(), []int{4}
}

func (x *FlowCreateRespond) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FlowSaveRespond struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FlowSaveRespond) Reset() {
	*x = FlowSaveRespond{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_flow_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlowSaveRespond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowSaveRespond) ProtoMessage() {}

func (x *FlowSaveRespond) ProtoReflect() protoreflect.Message {
	mi := &file_protos_flow_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowSaveRespond.ProtoReflect.Descriptor instead.
func (*FlowSaveRespond) Descriptor() ([]byte, []int) {
	return file_protos_flow_proto_rawDescGZIP(), []int{5}
}

type FlowLoadRespond struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *FlowLoadRespond) Reset() {
	*x = FlowLoadRespond{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_flow_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlowLoadRespond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowLoadRespond) ProtoMessage() {}

func (x *FlowLoadRespond) ProtoReflect() protoreflect.Message {
	mi := &file_protos_flow_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowLoadRespond.ProtoReflect.Descriptor instead.
func (*FlowLoadRespond) Descriptor() ([]byte, []int) {
	return file_protos_flow_proto_rawDescGZIP(), []int{6}
}

func (x *FlowLoadRespond) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FlowLoadRespond) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FlowLoadRespond) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type FlowDeleteRespond struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FlowDeleteRespond) Reset() {
	*x = FlowDeleteRespond{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_flow_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlowDeleteRespond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowDeleteRespond) ProtoMessage() {}

func (x *FlowDeleteRespond) ProtoReflect() protoreflect.Message {
	mi := &file_protos_flow_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowDeleteRespond.ProtoReflect.Descriptor instead.
func (*FlowDeleteRespond) Descriptor() ([]byte, []int) {
	return file_protos_flow_proto_rawDescGZIP(), []int{7}
}

var File_protos_flow_proto protoreflect.FileDescriptor

var file_protos_flow_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x09, 0x66, 0x6c, 0x6f, 0x77, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x27,
	0x0a, 0x11, 0x46, 0x6c, 0x6f, 0x77, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x49, 0x0a, 0x0f, 0x46, 0x6c, 0x6f, 0x77, 0x53,
	0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x25, 0x0a, 0x0f, 0x46, 0x6c, 0x6f, 0x77, 0x4c, 0x6f, 0x61, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x23, 0x0a, 0x11, 0x46, 0x6c, 0x6f,
	0x77, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x23,
	0x0a, 0x11, 0x46, 0x6c, 0x6f, 0x77, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x11, 0x0a, 0x0f, 0x46, 0x6c, 0x6f, 0x77, 0x53, 0x61, 0x76, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x22, 0x49, 0x0a, 0x0f, 0x46, 0x6c, 0x6f, 0x77, 0x4c, 0x6f,
	0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x13, 0x0a, 0x11, 0x46, 0x6c, 0x6f, 0x77, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x32, 0x99, 0x02, 0x0a, 0x0b, 0x46, 0x6c, 0x6f, 0x77, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x12, 0x1c, 0x2e, 0x66, 0x6c, 0x6f, 0x77, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x6c, 0x6f,
	0x77, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x66, 0x6c, 0x6f, 0x77, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x6c, 0x6f, 0x77, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x12, 0x3e, 0x0a, 0x04,
	0x53, 0x61, 0x76, 0x65, 0x12, 0x1a, 0x2e, 0x66, 0x6c, 0x6f, 0x77, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x46, 0x6c, 0x6f, 0x77, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x66, 0x6c, 0x6f, 0x77, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x6c, 0x6f,
	0x77, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x12, 0x3e, 0x0a, 0x04,
	0x4c, 0x6f, 0x61, 0x64, 0x12, 0x1a, 0x2e, 0x66, 0x6c, 0x6f, 0x77, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x46, 0x6c, 0x6f, 0x77, 0x4c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x66, 0x6c, 0x6f, 0x77, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x6c, 0x6f,
	0x77, 0x4c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x12, 0x44, 0x0a, 0x06,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1c, 0x2e, 0x66, 0x6c, 0x6f, 0x77, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x46, 0x6c, 0x6f, 0x77, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x66, 0x6c, 0x6f, 0x77, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x46, 0x6c, 0x6f, 0x77, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x64, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x66, 0x6c, 0x6f, 0x77, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_flow_proto_rawDescOnce sync.Once
	file_protos_flow_proto_rawDescData = file_protos_flow_proto_rawDesc
)

func file_protos_flow_proto_rawDescGZIP() []byte {
	file_protos_flow_proto_rawDescOnce.Do(func() {
		file_protos_flow_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_flow_proto_rawDescData)
	})
	return file_protos_flow_proto_rawDescData
}

var file_protos_flow_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_protos_flow_proto_goTypes = []interface{}{
	(*FlowCreateRequest)(nil), // 0: flowproto.FlowCreateRequest
	(*FlowSaveRequest)(nil),   // 1: flowproto.FlowSaveRequest
	(*FlowLoadRequest)(nil),   // 2: flowproto.FlowLoadRequest
	(*FlowDeleteRequest)(nil), // 3: flowproto.FlowDeleteRequest
	(*FlowCreateRespond)(nil), // 4: flowproto.FlowCreateRespond
	(*FlowSaveRespond)(nil),   // 5: flowproto.FlowSaveRespond
	(*FlowLoadRespond)(nil),   // 6: flowproto.FlowLoadRespond
	(*FlowDeleteRespond)(nil), // 7: flowproto.FlowDeleteRespond
}
var file_protos_flow_proto_depIdxs = []int32{
	0, // 0: flowproto.FlowService.Create:input_type -> flowproto.FlowCreateRequest
	1, // 1: flowproto.FlowService.Save:input_type -> flowproto.FlowSaveRequest
	2, // 2: flowproto.FlowService.Load:input_type -> flowproto.FlowLoadRequest
	3, // 3: flowproto.FlowService.Delete:input_type -> flowproto.FlowDeleteRequest
	4, // 4: flowproto.FlowService.Create:output_type -> flowproto.FlowCreateRespond
	5, // 5: flowproto.FlowService.Save:output_type -> flowproto.FlowSaveRespond
	6, // 6: flowproto.FlowService.Load:output_type -> flowproto.FlowLoadRespond
	7, // 7: flowproto.FlowService.Delete:output_type -> flowproto.FlowDeleteRespond
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_flow_proto_init() }
func file_protos_flow_proto_init() {
	if File_protos_flow_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_flow_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlowCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_flow_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlowSaveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_flow_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlowLoadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_flow_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlowDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_flow_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlowCreateRespond); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_flow_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlowSaveRespond); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_flow_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlowLoadRespond); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_flow_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlowDeleteRespond); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_flow_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_flow_proto_goTypes,
		DependencyIndexes: file_protos_flow_proto_depIdxs,
		MessageInfos:      file_protos_flow_proto_msgTypes,
	}.Build()
	File_protos_flow_proto = out.File
	file_protos_flow_proto_rawDesc = nil
	file_protos_flow_proto_goTypes = nil
	file_protos_flow_proto_depIdxs = nil
}
