# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  APP_NAME: cli
  VERSION: v1.0.0
  BIN_DIR: dist
  SOURCE_PATH: main.go

tasks:
  copy:worker:
    cmds:
      - task: ensure-dir
        vars:
          DIR: embedded/embeddedJS
      - cmd: cp ../../packages/worker-js/dist/main.cjs embedded/embeddedJS/worker.cjs.embed
        platforms: [linux, darwin]
      - cmd: cmd /c copy "..\\..\\packages\\worker-js\\dist\\main.cjs" "embedded\\embeddedJS\\worker.cjs.embed"
        platforms: [windows]

  ensure-dir:
    internal: true
    silent: true
    cmds:
      - cmd: mkdir -p {{.DIR}}
        platforms: [linux, darwin]
      - cmd: cmd /c if not exist "{{.DIR}}" mkdir "{{.DIR}}"
        platforms: [windows]

  build:release:
    desc: Build release binary with version and platform
    env:
      CGO_ENABLED: 0
    vars:
      VERSION_DEFAULT:
        sh: node -e "console.log(require('./package.json').version)"
      GOOS_DEFAULT:
        sh: go env GOOS
      GOARCH_DEFAULT:
        sh: go env GOARCH
    cmds:
      - task: ensure-dir
        vars:
          DIR: dist
      - go build -o {{.BIN_DIR}}/devtools-cli-{{.VERSION | default .VERSION_DEFAULT}}-{{.PLATFORM | default (printf "%s-%s" .GOOS_DEFAULT .GOARCH_DEFAULT)}}{{.BINARY_SUFFIX}} main.go

  clean:
    desc: Clean build artifacts
    cmds:
      - cmd: rm -rf {{.BIN_DIR}}
        platforms: [linux, darwin]
      - cmd: cmd /c rd /s /q "{{.BIN_DIR}}"
        platforms: [windows]
        ignore_error: true
