# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  APP_NAME: cli
  VERSION: v1.0.0
  BIN_DIR: dist
  SOURCE_PATH: main.go
  PLATFORMS:
    sh: jq --raw-output 'keys[]' platforms.json

tasks:
  copy:worker:
    cmds:
      - task: ensure-dir
        vars:
          DIR: embeded/embededJS
      - cmd: cp ../../packages/worker-js/dist/main.cjs embeded/embededJS/worker.cjs.embed
        platforms: [linux, darwin]
      - cmd: copy "..\\..\\packages\\worker-js\\dist\\main.cjs" "embeded\\embededJS\\worker.cjs.embed"
        platforms: [windows]

  ensure-dir:
    internal: true
    silent: true
    cmds:
      - cmd: mkdir -p {{.DIR}}
        platforms: [linux, darwin]
      - cmd: cmd /c if not exist "{{.DIR}}" mkdir "{{.DIR}}"
        platforms: [windows]

  clean:
    desc: Clean build artifacts
    cmd: rm -rf {{.BIN_DIR}}

  build:*:
    desc: Build for specified platform
    vars:
      PLATFORM: '{{index .MATCH 0}}'
      ENV:
        sh: >-
          jq --raw-output \
            '."{{.PLATFORM}}".go
              | to_entries
              | map("\(.key)=\(.value)")
              | join(" ")' \
            platforms.json
      BINARY_SUFFIX:
        sh: >-
          jq --raw-output \
            '."{{.PLATFORM}}"."binary-suffix" // ""' \
            platforms.json
    cmds:
      - >-
        {{.ENV}} go build \
          -ldflags="-X main.Version={{.VERSION}}" \
          -o {{.BIN_DIR}}/{{.APP_NAME}}-{{.PLATFORM}}{{.BINARY_SUFFIX}} \
          {{.SOURCE_PATH}}

  build:all:
    desc: Build for all platforms

    deps:
      - for:
          var: PLATFORMS
        task: 'build:{{.ITEM}}'
