name: Integration

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v12
      - uses: DeterminateSystems/magic-nix-cache-action@v7

      - name: Install Nix dependencies
        run: nix develop .#runner --command true

      - name: Install PNPM dependencies
        run: nix develop .#runner --command pnpm install

      - name: Lint
        run: nix develop .#runner --command pnpm lint
