name: Integration

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v12
      - uses: DeterminateSystems/magic-nix-cache-action@v7

      - name: Load Nix runner shell environment
        run: nix run .#gha-nix-develop -- .#runner

      - name: Install PNPM dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint
