name: Release

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  DOTENV_PRIVATE_KEY: ${{ secrets.DOTENV_PRIVATE_KEY }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: write
      id-token: write
      issues: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup runner environment
        uses: ./.github/actions/setup

      - name: Setup Git user
        # Use public GitHub bot user:
        # https://api.github.com/users/github-actions[bot]
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Version projects and trigger specialized release workflows
        run: pnpm nx run scripts:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
