name: Release / Chrome Extension

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  DOTENV_PRIVATE_KEY: ${{ secrets.DOTENV_PRIVATE_KEY }}
  DOTENV_PRIVATE_KEY_PRODUCTION: ${{ secrets.DOTENV_PRIVATE_KEY_PRODUCTION }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup runner environment
        uses: ./.github/actions/setup

      - id: info
        name: Get project information
        run: pnpm nx run scripts:project-info-output

      - name: Build
        run: pnpm nx run ${{ steps.info.outputs.NAME }}:build

      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: ${{ steps.info.outputs.ROOT }}/dist/*.zip
          if-no-files-found: error

  publish:
    name: Publish to Chrome Webstore
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
          pattern: chrome-mv3-prod.zip

      - uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.BPP_KEYS }}
          chrome-file: chrome-mv3-prod.zip
