name: Release

on:
  workflow_dispatch:
    inputs:
      api-recorder-extension: { type: boolean }
      desktop: { type: boolean }
      web: { type: boolean }

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup runner environment
        uses: ./.github/actions/setup

      - name: Setup Git user
        # Use public GitHub bot user:
        # https://api.github.com/users/github-actions[bot]
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Version projects and trigger specialized release workflows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gha-scripts release \
            ${{ inputs.api-recorder-extension && 'api-recorder-extension' || '' }} \
            ${{ inputs.desktop && 'desktop' || '' }} \
            ${{ inputs.web && 'web' || '' }} \
