name: Release / Cloudflare Pages

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    name: Publish to Cloudflare Pages
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup runner environment
        uses: ./.github/actions/setup

      - id: info
        name: Get project information
        run: gha-scripts export-project-info

      - name: Build
        run: pnpm nx run ${{ steps.info.outputs.NAME }}:build

      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ steps.info.outputs.NAME }}
          directory: ${{ steps.info.outputs.ROOT }}/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.NODE_ENV }}
          wranglerVersion: '3'
