name: Release

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  DOTENV_PRIVATE_KEY: ${{ secrets.DOTENV_PRIVATE_KEY }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: write
      id-token: write
      issues: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup runner environment
        uses: ./.github/actions/setup

      - name: Version projects and trigger specialized release workflows
        run: nx run scripts:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
