name: Version

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  DOTENV_PRIVATE_KEY: ${{ secrets.DOTENV_PRIVATE_KEY }}

jobs:
  version:
    name: Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # https://github.com/changesets/action/issues/187#issuecomment-1228413850
          token: ${{ secrets.CHANGESET_GITHUB_TOKEN }}

      - name: Setup
        uses: ./.github/actions/setup

      - name: Create version pull request
        uses: changesets/action@v1
        with:
          publish: pnpm changeset tag
        env:
          # https://github.com/changesets/action/issues/187#issuecomment-1228413850
          GITHUB_TOKEN: ${{ secrets.CHANGESET_GITHUB_TOKEN }}
