name: Version

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  DOTENV_PRIVATE_KEY: ${{ secrets.DOTENV_PRIVATE_KEY }}

jobs:
  version:
    name: Version
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      issues: read
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # https://github.com/changesets/action/issues/187#issuecomment-1228413850
          token: ${{ secrets.CHANGESET_GITHUB_TOKEN }}

      - name: Setup runner environment
        uses: ./.github/actions/setup

      - name: Create version pull request
        # https://github.com/changesets/action/issues/192#issuecomment-2070377713
        uses: the-dev-tools/changesets-action@v1
        with:
          publish: pnpm changeset tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
